function to send chunked responses
utopia-php/swoole pull request #3
Opened 2021-07-11 12:12 UTC by lohanidamodar

Send responses in multiple chunks. pass `$last` true to end the response

2021-07-12 09:19 UTC, TorstenDittmann approved these changes

2021-07-12 09:19 UTC, TorstenDittmann commented on tests/e2e/server.php
> +        var_dump($response);
leftover.

2021-07-12 09:19 UTC, TorstenDittmann commented on tests/e2e/server.php
> +    // var_dump($request);
leftover.

2021-07-12 09:31 UTC, lohanidamodar commented on tests/e2e/server.php
> +        var_dump($response);
removed

2021-07-12 09:31 UTC, lohanidamodar commented on tests/e2e/server.php
> +    // var_dump($request);
removed

2021-07-16 10:25 UTC, eldadfux commented on src/Swoole/Response.php
> +    public function chunk(string $body = '', bool $last = false): void
Any chance this should or could be part of utopia/fw i a way that we can keep a consistent interface?

2021-07-16 10:25 UTC, eldadfux commented on src/Swoole/Response.php
> +    public function chunk(string $body = '', bool $last = false): void
```suggestion
    public function chunk(string $body = '', bool $end = false): void
```

Might be more decoupled from the files behavior and a bit more generic.

2021-07-21 12:10 UTC, eldadfux requested changes

2021-07-23 04:54 UTC, eldadfux approved these changes
Waiting for the release of utopia/fw

2021-07-26 06:37 UTC, eldadfux approved these changes

2021-07-26 06:41 UTC, merged